### ISSUE TITLE
Post-jobs script doesn't work?

### ISSUE THREAD

**Issue by Thormir84** [grufocom/vee-mail#41] opened 2023-02-16 09:55 UTC
I have 5 NAS based on OMV (OpenMediaVault) with the latest version of Veeam Agent installed.

With the new release of vee-mail (0.5.46) i have a strange issue.

With 2 NAS all works perfectly; after every backup one mail is sent with the results.

With 3 NAS no mail is sent.

The configuration of the script in the 5 NAS is exactly the same; same mail but different "JOBNAME"

With "/opt/vee-mail/vee-mail.sh" from terminal, i receive a mail from every NAS without problems.

Removing e reinstalling the Veeam Agent doesn't resolve.

Is not a permission issue; alla NAS has the same configuration and the same version of OMV installed.

Any ideas?

**Comment by tom666-debug** [comment] 2023-02-17 07:07
Hi,
I am experiencing the same issue here, script (vee-mail.sh) runs as expected when started from shell but as a "post-job" configured in Veeam does not work anymore.

This is the additional output when I run the script with DEBUG=1:

STARTTIME: 1676616977, ENDTIME: 1676617024, STATE: 6, JOBID: {bbc42396-6d2f-4c93-8667-2cbbc5f27207}, JOBNAME: BackupJob1
DETAILS: <ProgressDetails total_size="275837378560" total_used_size="35241758720" processed_data_size_bytes="923903885" read_data_size_bytes="57747" transferred_data_size_bytes="127152008" processing_speed="4015" source_read_load="0" source_processing_load="0" network_load="0" target_write_load="94" network_throttling_enabled="false" repository_throttling_enabled="false" />
TARGET: , FST: , LOGIN: , DOMAIN:
PROCESSED: 0.9 GB, READ: 0.0 GB, TRANSFERRED: 127152008
SPEED: 0.0, SOURCELOAD: 0, NETLOAD: 0, TARGETLOAD: 94
DURATION: 0:00:47, START: Freitag, 17 Februar 2023 07:56:17, END: Freitag, 17.02.2023 07:57:04, STIME: 07:56:17, ETIME: 07:57:04
ERRLOG:
HN: MY_HOSTNAME_GOES_HERE
STAT: Success
BGCOLOR: #00B050
START: Freitag, 17 Februar 2023 07:56:17
SUCCESS: 1
ERROR: 0
WARNING: 0
STIME: 07:56:17
ETIME: 07:57:04
READ: 0.0 GB
TRANSFERRED: 121 MB
DURATION: 0:00:47
PROCESSED: 0.9 GB
BOTTLENECK: Target
ERRLOG:
SPEED: 0.0
TARGET: /mnt/Backup
FST: cifs
LOGIN:
DOMAIN:
 DEVUSEP: 68%

**Comment by grufocom** [comment] 2023-02-17 08:30
Debug output looks good!
Which Veeam version do you have installed?

**Comment by tom666-debug** [comment] 2023-02-17 08:41
Veeam Agent for Linux:
Version: 6.0.0.1060
Build edition: standard
Build date: 06/02/2023

Let me know if I can provide any additional informations.

**Comment by grufocom** [comment] 2023-02-17 08:47
you could try to start the vee-mail.sh with this post command in the background:
sleep 30 && sh /opt/vee-mail/vee-mail.sh &

if it does not work as a post command in veeam, please try to put it in a bash script and start that bash script.

**Comment by tom666-debug** [comment] 2023-02-17 08:55
sleep 30 && sh /opt/vee-mail/vee-mail.sh & is not working (see attached output):

root@MY_SERVER:/opt/vee-mail# sleep 30 && sh /opt/vee-mail/vee-mail.sh &
[1] 47688
root@MY_SERVER:/opt/vee-mail# /opt/vee-mail/vee-mail.sh: 10: /opt/vee-mail/vee-mail.sh: [[: not found
/opt/vee-mail/vee-mail.sh: 19: [: unexpected operator
/opt/vee-mail/vee-mail.sh: 90: /opt/vee-mail/vee-mail.sh: Bad substitution
^C
[1]+  Exit 2                  sleep 30 && sh /opt/vee-mail/vee-mail.sh

just executing ./vee-mail.sh is still working

**Comment by grufocom** [comment] 2023-02-17 08:58
OK, please try to use "bash" instead of "sh"! :-)

**Comment by tom666-debug** [comment] 2023-02-17 09:04
root@MY_SERVER:/opt/vee-mail# sleep 30 && bash /opt/vee-mail/vee-mail.sh &
[1] 52572
root@MY_SERVER:/opt/vee-mail#

went through without errors now, also the email arrived as expected ;-)

**Comment by grufocom** [comment] 2023-02-17 09:06
perfect! :-)
@Thormir84 I hope this helps you too, please try and give feedback.

**Comment by tom666-debug** [comment] 2023-02-17 09:17
So we are a step further now.... good :-) 
But what is the (temporary) solution now - build my own bash script that calls vee-mail.sh?

**Comment by grufocom** [comment] 2023-02-17 09:19
yes, please try that!

```
#!/bin/bash
sleep 30 && bash /opt/vee-mail/vee-mail.sh &
```

**Comment by tom666-debug** [comment] 2023-02-17 09:25
I can confirm that this is working now (new bash script configured as post job in Veeam). Thx for your quick support!
Question, will this be a temporary solution or is this the final fix already?

**Comment by grufocom** [comment] 2023-02-17 09:32
normaly vee-mail will determine how it was started (ps -p $PPID -hco cmd) and if it is started from veeamjobman then it waits 30 seconds and starts itself again in background.
I don't know why this does not happen on your system, I can not reproduce it on mine. 
if we find the reason I am willing to fix that problem! :-)

you could grep your syslog  for vee-mail messages (grep vee-mail /var/log/syslog) if there is a vee-mail "waiting for 30 seconds" then the script tries to start itself in background.

**Comment by Thormir84** [comment] 2023-02-17 10:45
> perfect! :-) @Thormir84 I hope this helps you too, please try and give feedback.

Yes, i confirm that it works; i've created a "vee-mail-FIX.sh" with the script and now all works.

Thanks!

**Comment by pewkodi** [comment] 2023-02-19 19:19
I have a Fedora 36 system and I added this to determine which $VV to use:

if "dpkg -l"; then
echo "Using dpkg"
VV=$(dpkg -l|grep " veeam " |awk '{print $3}'|awk -F'.' '{print $1}')
else
echo "Using RPM instead"
VV=$(rpm -qa |grep "veeam" |awk -F- '{print $3}'|awk -F'.' '{print $1}' | tail -1 )
fi


I also just added the sleep to the main script.

VERSION=0.5.46
HDIR=$(dirname "$0")
DEBUG=0
INFOMAIL=1
# INFOMAIL 1=ALWAYS (DEFAULT), 2=WARN, 3=ERROR
SENDM=0

sleep 30

**Comment by grufocom** [comment] 2023-02-20 07:05
@pewkodi 
wouldn't that work too?:
`rpm -q veeam|awk '{print $3}'|awk -F'.' '{print $1}'`

The sleep function is implemented in the script, it should fork itself and sleep for 30 seconds.
If you have a line with "waiting for 30 seconds" in your syslog then that works.
Maybe the 30 seconds are to low for your system - if that is the case I would change my script to set a custom value for sleep in the config file.

Can you adjust the sleep command in line 22 and try that?

**Comment by pewkodi** [comment] 2023-02-21 01:31
Hello 

I took away the sleep and it is functioning. 

This is the output for the suggested rpm command.

root@PWLINUX-LAP vee-mail]# rpm -q veeam|awk '{print $3}'|awk -F'.' '{print $1}'
is
This is not correct.

You need the veeam version installed.

[root@PWLINUX-LAP vee-mail]# rpm -qa |grep "veeam" |awk -F- '{print $3}'|awk -F'.' '{print $1}'
el8
6
[root@PWLINUX-LAP vee-mail]# rpm -qa |grep "veeam" |awk -F- '{print $3}'|awk -F'.' '{print $1}' | tail -1
6


Or use the command veeamconfig -v

**Comment by grufocom** [comment] 2023-02-21 10:19
to check the version with veeamconfig is a very good idea! thx :-)
I changed that in version 0.5.47

**Closed by grufocom** 2023-02-21 10:19 UTC
